Parameters:
  repoName:
    Description: The name of the ECR repository
    Type: String
Resources:
  ECRRepo:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: !Sub ${repoName}
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              AWS: 
                - "arn:aws:iam::925885294484:user/raffaeu-devops"
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
Outputs:    
  Arn:
    Value: !GetAtt ECRRepo.Arn
  Uri:
    Value: !GetAtt ECRRepo.RepositoryUri